const assert = require("node:assert/strict");
const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");
const test = require("node:test");

const { Fabricator, createSpinner, formatBytes, generate, writeDocuments, writeDocumentsLive } = require("../generator");
const { deferredFunction } = require("../parser");

const definitionsDirectory = path.join(__dirname, "..", "definitions");
const baseConfig = { maxDepth: 1, maxArrayLength: 1 };

test("generates inherited classes and schema-aware functions", () => {
  const documents = generate("<class:Car>", { config: baseConfig });
  assert.equal(documents.length, 20);
  assert.ok(documents.every((document) => document.numberPlate === ""));
  assert.ok(documents.every((document) => document.oneMoreThanSpeed === document.speed + 1));
  assert.ok(documents.every((document) => document.sortedColors.join(",") === "blue,green,red"));
});

test("expands tags and optional properties at every nesting level", () => {
  const fabricator = new Fabricator(definitionsDirectory, baseConfig);
  fabricator.loader.functionCache.set("constant", () => () => "computed");
  const documents = fabricator.generate({
    nested: {
      color: "<enum:Color>",
      "label?": "<function:constant>",
      fixed: ["<Number>", "<Boolean>"],
    },
  });
  assert.equal(documents.length, 6);
  assert.ok(documents.some(({ nested }) => !Object.hasOwn(nested, "label")));
  assert.ok(documents.some(({ nested }) => nested.label === "computed"));
  assert.ok(documents.every(({ nested }) => nested.fixed[0] === 0 && nested.fixed[1] === false));
});

test("builds an exact multiplicative possibility tree", () => {
  const fabricator = new Fabricator(definitionsDirectory, baseConfig);
  const tree = fabricator.buildPossibilityTree("<class:Driver>");
  assert.equal(tree.type, "class");
  assert.equal(tree.name, "Driver");
  assert.equal(tree.possibilities, 15n);
});

test("passes multiple schema arguments to functions", () => {
  const fabricator = new Fabricator(definitionsDirectory, baseConfig);
  fabricator.loader.functionCache.set("combine", () => (vehicle, colors) => `${vehicle.speed}:${colors[0]}`);
  const value = deferredFunction("combine", ["schema.class.Vehicle", "schema.enum.Color"]);
  assert.equal(fabricator.materializeFunction(value, new Map([["Vehicle", { speed: 12 }]])), "12:red");
});

test("streams generated documents to the output directory", () => {
  const outputDirectory = fs.mkdtempSync(path.join(os.tmpdir(), "schema-fabricator-output-"));
  try {
    const progress = [];
    fs.writeFileSync(path.join(outputDirectory, "tree-000000000099.json"), "stale");
    fs.writeFileSync(path.join(outputDirectory, "notes.txt"), "stale");
    assert.equal(writeDocuments([{ id: 1 }, { id: 2 }], outputDirectory, {
      onProgress: (status) => progress.push(status),
    }), 2);
    assert.deepEqual(fs.readdirSync(outputDirectory).sort(), [
      "tree-000000000001.json",
      "tree-000000000002.json",
    ]);
    assert.deepEqual(JSON.parse(fs.readFileSync(path.join(outputDirectory, "tree-000000000002.json"), "utf8")), { id: 2 });
    assert.deepEqual(progress.map(({ count }) => count), [0, 1, 2]);
    assert.ok(progress.at(-1).bytes > 0);
  } finally {
    fs.rmSync(outputDirectory, { recursive: true, force: true });
  }
});

test("yields to the event loop while streaming live output", async () => {
  const outputDirectory = fs.mkdtempSync(path.join(os.tmpdir(), "schema-fabricator-live-output-"));
  try {
    let yielded = false;
    setImmediate(() => { yielded = true; });
    await writeDocumentsLive(Array.from({ length: 100 }, (_, id) => ({ id })), outputDirectory);
    assert.equal(yielded, true);
  } finally {
    fs.rmSync(outputDirectory, { recursive: true, force: true });
  }
});

test("formats generated byte counts for progress output", () => {
  assert.equal(formatBytes(0), "0 B");
  assert.equal(formatBytes(1024), "1.00 KB");
  assert.equal(formatBytes(1024 ** 2), "1.00 MB");
});

test("includes live details in non-TTY spinner output", () => {
  let output = "";
  const spinner = createSpinner("Generating documents", {
    isTTY: false,
    write: (line) => { output += line; },
  });
  spinner.start();
  spinner.update("12  1.00 KB");
  spinner.stop();
  assert.match(output, /⠋ Generating documents:/);
  assert.match(output, /✓ Generating documents: 12  1\.00 KB/);
});

test("shares loaded state across functions", () => {
  const temporaryDefinitions = fs.mkdtempSync(path.join(os.tmpdir(), "schema-fabricator-state-"));
  try {
    fs.cpSync(definitionsDirectory, temporaryDefinitions, { recursive: true });
    const stateDirectory = path.join(temporaryDefinitions, "state");
    fs.mkdirSync(stateDirectory, { recursive: true });
    fs.writeFileSync(path.join(stateDirectory, "Counter.state.json"), JSON.stringify({ value: 0 }));

    const fabricator = new Fabricator(temporaryDefinitions, baseConfig);
    fabricator.loader.functionCache.set("increment", (schema) => () => ++schema.state.Counter.value);
    fabricator.loader.functionCache.set("read", (schema) => () => schema.state.Counter.value);
    assert.deepEqual(fabricator.generate({ first: "<function:increment>", second: "<function:read>" }), [{ first: 1, second: 1 }]);
  } finally {
    fs.rmSync(temporaryDefinitions, { recursive: true, force: true });
  }
});

test("validates malformed tags and circular unions", () => {
  for (const token of ["<class>", "<union>", "<enum>", "<function>"]) {
    assert.throws(() => generate(token, { config: baseConfig }), /token must include a name/);
  }
  const fabricator = new Fabricator(definitionsDirectory, baseConfig);
  fabricator.classes.set("Loop", {
    filename: "<memory>/Loop.class.json",
    name: "Loop",
    properties: { child: "<union:Loop>" },
  });
  fabricator.unions.set("Loop", ["<class:Loop>"]);
  assert.throws(() => [...fabricator.generateTrees("<union:Loop>")], /Circular union: Loop/);
});
